# Generated by Django 4.0.2 on 2022-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='Address Nahi Diya', max_length=122),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='combos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='combos',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='price',
            field=models.IntegerField(),
        ),
    ]
