# Generated by Django 4.0.2 on 2022-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_orders_address_alter_beverages_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
            ],
        ),
    ]
