# Generated by Django 4.0.2 on 2022-03-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalamount',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
