# Generated by Django 4.0.2 on 2022-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_orders_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
