# Generated by Django 4.0.2 on 2022-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='desr',
            field=models.TextField(default='Kuch extra ni chiye', max_length=300),
        ),
    ]
