# Generated by Django 4.0.2 on 2022-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_orders_desr'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='productId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='productType',
            field=models.IntegerField(default=3),
        ),
    ]
